// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvTNsEULFKxS4wCuWlrWZxNxeuqbkXlz0',
    appId: '1:314456515681:web:895ee46672f846d596f620',
    messagingSenderId: '314456515681',
    projectId: 'naviostest-93523',
    authDomain: 'naviostest-93523.firebaseapp.com',
    storageBucket: 'naviostest-93523.appspot.com',
    measurementId: 'G-7ZDW32Q8B6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJM33I9_MB-Fdll5mz13hyuQDAfsc3d1M',
    appId: '1:314456515681:android:b8badec37dedec8696f620',
    messagingSenderId: '314456515681',
    projectId: 'naviostest-93523',
    storageBucket: 'naviostest-93523.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvk1caNbaoO9MejQWGRoNnjb5kMRH5IA4',
    appId: '1:314456515681:ios:6e8d3642a811e50e96f620',
    messagingSenderId: '314456515681',
    projectId: 'naviostest-93523',
    storageBucket: 'naviostest-93523.appspot.com',
    iosBundleId: 'com.example.naviosTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvk1caNbaoO9MejQWGRoNnjb5kMRH5IA4',
    appId: '1:314456515681:ios:cac6acffadab6b4c96f620',
    messagingSenderId: '314456515681',
    projectId: 'naviostest-93523',
    storageBucket: 'naviostest-93523.appspot.com',
    iosBundleId: 'com.example.naviosTest.RunnerTests',
  );
}
